### ISSUE TITLE
uvloop 라이브러리 호환성 문제

### ISSUE THREAD

**Issue by 1105nam** [cau-oss-team3/narae#1]
### 이슈요약
- uvloop 라이브러리가 Windows에서 [지원하지 않는 문제](https://github.com/MagicStack/uvloop/issues/536#issuecomment-1553968437)가 있음.

### 해결방안(제안)

- 대체 라이브러리 [Winloop](https://github.com/Vizonex/Winloop) 사용
- 성능향상을 포기하고 asyncio 라이브러리 사용
- 리눅스 가상환경 또는 WSL 환경에서 개발

### 에러 메시지 전문
```Collecting uvloop==0.19.0
  Using cached uvloop-0.19.0.tar.gz (2.3 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'

  error: subprocess-exited-with-error
  
  Getting requirements to build wheel did not run successfully.
  exit code: 1
  
  [18 lines of output]
  Traceback (most recent call last):
    File "D:\Dev\OSS\narae\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "D:\Dev\OSS\narae\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "D:\Dev\OSS\narae\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
             ^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\nam\AppData\Local\Temp\pip-build-env-1p1m91gk\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\nam\AppData\Local\Temp\pip-build-env-1p1m91gk\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
      self.run_setup()
    File "C:\Users\nam\AppData\Local\Temp\pip-build-env-1p1m91gk\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
      exec(code, locals())
    File "<string>", line 8, in <module>
  RuntimeError: uvloop does not support Windows at the moment
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

Getting requirements to build wheel did not run successfully.
exit code: 1

See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```
@IamGroooooot

**Comment by IamGroooooot** [comment]
`uvicorn`을 설치하면서 갖게 된 의존성인데 찾아보니 uvloop은 필수적이지 않다고 합니다.
해당 의존성은 [커밋](https://github.com/cau-oss-team3/narae/commit/b1b4090c0ed27090ee1e2fd2deb9d5a43dd303f2)에서 삭제했습니다.

참고: https://stackoverflow.com/questions/70731019/is-it-impossible-developing-with-fastapi-uvloop-windows
